import { useState, useRef, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAppStore } from '../store/appStore'
import PromptLibrary from '../components/PromptLibrary'
import CompareView from '../components/CompareView'

export default function ChatPage() {
  const navigate = useNavigate()
  const {
    installedModels,
    selectedModelPath,
    selectedModelName,
    setSelectedModel,
    conversations,
    activeConversationId,
    createConversation,
    sendMessage,
    regenerateLastResponse,
    isGenerating,
    streamingText,
    activePersona,
    setActivePersona,
    compareMode,
    setCompareMode
  } = useAppStore()

  const [input, setInput] = useState('')
  const [personas, setPersonas] = useState<PersonaData[]>([])
  const [promptLibOpen, setPromptLibOpen] = useState(false)
  const [showExportMenu, setShowExportMenu] = useState(false)
  const [exportStatus, setExportStatus] = useState('')
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  const activeConvo = conversations.find((c) => c.id === activeConversationId)
  const messages = activeConvo?.messages ?? []
  const noModels = installedModels.length === 0
  const hasMessages = messages.length > 0
  const canCompare = installedModels.length >= 1

  useEffect(() => {
    window.airoost.getPersonas().then(setPersonas)
  }, [])

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, streamingText])

  useEffect(() => {
    inputRef.current?.focus()
  }, [activeConversationId])

  // Render compare mode (after all hooks)
  if (compareMode) return <CompareView />

  // Close export menu on outside click
  useEffect(() => {
    if (!showExportMenu) return
    const close = () => setShowExportMenu(false)
    window.addEventListener('click', close)
    return () => window.removeEventListener('click', close)
  }, [showExportMenu])

  const handleSend = async () => {
    if (!input.trim() || isGenerating || noModels) return
    const msg = input.trim()
    setInput('')
    if (!activeConversationId) createConversation()
    await sendMessage(msg)
  }

  const handleCopy = (text: string) => navigator.clipboard.writeText(text)

  const handleCopyAsMarkdown = (text: string) => {
    navigator.clipboard.writeText(`> ${text.replace(/\n/g, '\n> ')}`)
  }

  const handleCopySnippet = (text: string) => {
    const model = activeConvo?.modelId ?? 'AI'
    const snippet = `> ${text.replace(/\n/g, '\n> ')}\n\n\u2014 *Generated by ${model} via Airoost*`
    navigator.clipboard.writeText(snippet)
  }

  const getExportData = () => {
    if (!activeConvo) return null
    return {
      title: activeConvo.title,
      modelId: activeConvo.modelId,
      personaName: activeConvo.personaName,
      personaEmoji: activeConvo.personaEmoji,
      createdAt: activeConvo.createdAt,
      messages: activeConvo.messages.map((m) => ({ role: m.role, content: m.content }))
    }
  }

  const handleExportPDF = async () => {
    const data = getExportData()
    if (!data) return
    setExportStatus('Generating PDF...')
    setShowExportMenu(false)
    try {
      const path = await window.airoost.exportPDF(data)
      setExportStatus(path ? 'PDF saved!' : '')
    } catch {
      setExportStatus('Export failed')
    }
    setTimeout(() => setExportStatus(''), 2000)
  }

  const handleExportDOCX = async () => {
    const data = getExportData()
    if (!data) return
    setExportStatus('Generating Word...')
    setShowExportMenu(false)
    try {
      const path = await window.airoost.exportDOCX(data)
      setExportStatus(path ? 'Word file saved!' : '')
    } catch {
      setExportStatus('Export failed')
    }
    setTimeout(() => setExportStatus(''), 2000)
  }

  const handleExportMarkdown = async () => {
    const data = getExportData()
    if (!data) return
    setShowExportMenu(false)
    const md = await window.airoost.exportMarkdown(data)
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${activeConvo!.title.replace(/[^a-z0-9]/gi, '_')}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleCopyAll = async () => {
    const data = getExportData()
    if (!data) return
    setShowExportMenu(false)
    const text = await window.airoost.exportText(data)
    navigator.clipboard.writeText(text)
    setExportStatus('Copied!')
    setTimeout(() => setExportStatus(''), 2000)
  }

  const isBundledModel = selectedModelName?.includes('Phi-3')

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center gap-3 px-5 py-3 border-b border-white/5">
        {/* Model selector */}
        <select
          value={selectedModelPath ?? ''}
          onChange={(e) => {
            const model = installedModels.find((m) => m.path === e.target.value)
            if (model) setSelectedModel(model.path, model.name)
          }}
          className="bg-surface-dark border border-white/10 text-white text-xs rounded-lg px-3 py-1.5 outline-none"
        >
          {noModels && <option value="">No models installed</option>}
          {installedModels.map((m) => (
            <option key={m.path} value={m.path}>{m.name}</option>
          ))}
        </select>

        {/* Persona selector */}
        <select
          value={activePersona?.id ?? ''}
          onChange={(e) => {
            const p = personas.find((p) => p.id === e.target.value)
            setActivePersona(p ?? null)
          }}
          className="bg-surface-dark border border-white/10 text-white text-xs rounded-lg px-3 py-1.5 outline-none"
        >
          <option value="">No Persona</option>
          {personas.map((p) => (
            <option key={p.id} value={p.id}>{p.emoji} {p.name}</option>
          ))}
        </select>

        {activePersona && (
          <span className="text-[11px] text-accent/70">{activePersona.emoji} {activePersona.name}</span>
        )}

        {/* Spacer */}
        <div className="flex-1" />

        {/* Export status */}
        {exportStatus && (
          <span className="text-[11px] text-accent animate-pulse">{exportStatus}</span>
        )}

        {/* Compare button */}
        {canCompare && (
          <button
            onClick={() => setCompareMode(true)}
            className="px-2.5 py-1.5 bg-white/5 hover:bg-accent/10 rounded-lg text-gray-400 hover:text-accent text-[11px] transition-colors flex items-center gap-1.5"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 21L3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5" />
            </svg>
            Compare
          </button>
        )}

        {/* Export button */}
        {hasMessages && (
          <div className="relative">
            <button
              onClick={(e) => { e.stopPropagation(); setShowExportMenu(!showExportMenu) }}
              className="px-2.5 py-1.5 bg-white/5 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white text-[11px] transition-colors flex items-center gap-1.5"
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              Export
            </button>
            {showExportMenu && (
              <div className="absolute right-0 top-9 w-44 bg-surface-dark border border-white/10 rounded-xl shadow-2xl py-1 z-50" onClick={(e) => e.stopPropagation()}>
                <ExportMenuItem label="Export as PDF" onClick={handleExportPDF} />
                <ExportMenuItem label="Export as Word" onClick={handleExportDOCX} />
                <ExportMenuItem label="Export as Markdown" onClick={handleExportMarkdown} />
                <div className="border-t border-white/5 my-1" />
                <ExportMenuItem label="Copy All" onClick={handleCopyAll} />
              </div>
            )}
          </div>
        )}

        {isBundledModel && !activePersona && !hasMessages && (
          <button
            onClick={() => navigate('/models')}
            className="text-[11px] text-gray-500 hover:text-accent transition-colors"
          >
            Running Phi-3 Mini {'\u2014'} explore more powerful models in the library {'\u2192'}
          </button>
        )}
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
        {/* Empty state */}
        {messages.length === 0 && !isGenerating && (
          <div className="flex flex-col items-center justify-center h-full text-center">
            {noModels ? (
              <>
                <p className="text-gray-500 text-sm mb-4">Download a model to start chatting</p>
                <button
                  onClick={() => navigate('/models')}
                  className="px-5 py-2.5 bg-accent hover:bg-accent-dark rounded-lg text-white text-sm font-medium transition-colors"
                >
                  Browse Models
                </button>
              </>
            ) : (
              <>
                <h2 className="text-xl font-semibold text-white mb-1">
                  <span className="text-accent">Air</span>oost
                </h2>
                <p className="text-sm text-gray-500 mb-6">AI that stays home.</p>
                <div className="grid grid-cols-2 gap-3 max-w-sm">
                  {['Explain quantum computing simply', 'Write a haiku about coding', 'Help me plan a weekend trip', 'Summarize the theory of relativity'].map((prompt) => (
                    <button
                      key={prompt}
                      onClick={() => { setInput(prompt); inputRef.current?.focus() }}
                      className="text-left px-3 py-2.5 rounded-lg bg-white/5 hover:bg-white/10 text-xs text-gray-400 hover:text-gray-200 transition-colors"
                    >
                      {prompt}
                    </button>
                  ))}
                </div>
                {canCompare && (
                  <button
                    onClick={() => setCompareMode(true)}
                    className="mt-4 px-4 py-2 rounded-lg bg-accent/10 hover:bg-accent/20 text-xs text-accent transition-colors"
                  >
                    Try comparing two models {'\u2192'}
                  </button>
                )}
              </>
            )}
          </div>
        )}

        {/* Message bubbles */}
        {messages.map((msg, i) => (
          <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className="group relative max-w-[75%]">
              <div
                className={`px-4 py-3 rounded-2xl text-sm leading-relaxed ${
                  msg.role === 'user'
                    ? 'bg-accent text-white rounded-br-md'
                    : 'bg-surface text-gray-200 rounded-bl-md'
                }`}
              >
                <p className="whitespace-pre-wrap">{msg.content}</p>
              </div>

              {/* Actions on assistant messages */}
              {msg.role === 'assistant' && !isGenerating && (
                <div className="opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1 mt-1">
                  <ActionBtn label="Copy" onClick={() => handleCopy(msg.content)} />
                  <ActionBtn label="Copy MD" onClick={() => handleCopyAsMarkdown(msg.content)} />
                  <ActionBtn
                    label="Snippet"
                    onClick={() => handleCopySnippet(msg.content)}
                    title={'Copy as formatted snippet with model attribution'}
                  />
                  {i === messages.length - 1 && (
                    <ActionBtn label="Regenerate" onClick={regenerateLastResponse} />
                  )}
                </div>
              )}

              {/* Actions on user messages */}
              {msg.role === 'user' && !isGenerating && (
                <div className="opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-end gap-1 mt-1">
                  <ActionBtn label="Copy" onClick={() => handleCopy(msg.content)} />
                </div>
              )}
            </div>
          </div>
        ))}

        {/* Streaming response */}
        {isGenerating && (
          <div className="flex justify-start">
            <div className="max-w-[75%] bg-surface px-4 py-3 rounded-2xl rounded-bl-md text-sm text-gray-200 leading-relaxed">
              {streamingText ? (
                <p className="whitespace-pre-wrap">{streamingText}<span className="animate-pulse text-accent">{'\u258C'}</span></p>
              ) : (
                <div className="flex gap-1 py-1">
                  <span className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce" />
                  <span className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce [animation-delay:0.1s]" />
                  <span className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce [animation-delay:0.2s]" />
                </div>
              )}
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="px-5 py-4 border-t border-white/5">
        <div className="flex gap-3">
          <button
            onClick={() => setPromptLibOpen(true)}
            className="shrink-0 px-3 py-3 bg-surface border border-white/10 rounded-xl text-gray-500 hover:text-accent hover:border-accent/30 transition-colors"
            title="Prompt Library"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" />
            </svg>
          </button>
          <input
            ref={inputRef}
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && handleSend()}
            placeholder={noModels ? 'Download a model first...' : 'Type a message...'}
            disabled={noModels || isGenerating}
            className="flex-1 bg-surface border border-white/10 rounded-xl px-4 py-3 text-white text-sm placeholder-gray-600 outline-none focus:border-accent/50 transition-colors disabled:opacity-50"
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || noModels || isGenerating}
            className="px-5 py-3 bg-accent hover:bg-accent-dark rounded-xl text-white text-sm font-medium transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
          >
            Send
          </button>
        </div>
      </div>

      {/* Prompt Library Modal */}
      <PromptLibrary
        open={promptLibOpen}
        onClose={() => setPromptLibOpen(false)}
        onSelect={(text) => {
          setInput(text)
          setTimeout(() => inputRef.current?.focus(), 50)
        }}
      />
    </div>
  )
}

function ActionBtn({ label, onClick, title }: { label: string; onClick: () => void; title?: string }) {
  return (
    <button
      onClick={onClick}
      title={title}
      className="text-[10px] text-gray-600 hover:text-gray-300 px-2 py-0.5 rounded bg-white/5 transition-colors"
    >
      {label}
    </button>
  )
}

function ExportMenuItem({ label, onClick }: { label: string; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className="w-full text-left px-3 py-1.5 text-[11px] text-gray-300 hover:bg-white/5 transition-colors"
    >
      {label}
    </button>
  )
}
